apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
  labels:
    app: model
spec:
  replicas: 0
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: 015162308185.dkr.ecr.us-west-2.amazonaws.com/abalone:f34a5c18-2bc8-449d-8d87-69d660765f6d
        ports:
        - containerPort: 8080
