apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
  labels:
    app: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: 015162308185.dkr.ecr.us-west-2.amazonaws.com/abalone:15696a0e-a575-4dcf-8c3f-a7f106caf1af
        ports:
        - containerPort: 8080
